# WEB SCRAPING – ASSIGNMENT 4

In [1]:
# import necessary libraries at once

import pandas as pd
import selenium
import time
from bs4 import BeautifulSoup 
from selenium import webdriver
from selenium.webdriver.common.by import By

from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import Keys
import requests
import re
from selenium.webdriver.support.ui import WebDriverWait
import warnings
warnings.filterwarnings('ignore')

# Scrape the details of most viewed videos on YouTube from Wikipedia.
Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos
You need to find following details:
    A) Rank
    
    B) Name
    
    C) Artist
    
    D) Upload date
    
    E) Views

In [5]:
driver=webdriver.Chrome('chromedriver.exe')

In [6]:
# Getting the webpage of mentioned url 
url=('https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos')
driver.get(url)

In [32]:
# Creating empty list for storing data after scraping

Rank = []
Name = []
Artist = []
UploadDate = []
Views = []
# Scraping Rank of the videos
try:
    for i in driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[1]"):
        Rank.append(i.text)
except NoSuchElementException:
    Rank.append("_")
#scrapping rank
try:
    for i in driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[2]"):
        Name.append(i.text)
except NoSuchElementException:
    Name.append("_")
#scrapping Artist
try:
    for i in driver.find_elements_by_xpath('//*[@id="mw-content-text"]/div[1]/table[2]/tbody/tr/td[3]'):
        Artist.append(i.text)
except NoSuchElementException:
    Artist.append("_")
#Scrapping Date
try:
    for i in driver.find_elements_by_xpath(' //table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[5]'):
        UploadDate.append(i.text)
except NoSuchElementException:
    UploadDate.append('-')
# Scraping Views of videos
try:
    for i in driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[4]"):
        Views.append(i.text)
except NoSuchElementException:
    Views.append("_")

In [33]:
# Creating DataFrame from scraped data
Wiki = pd.DataFrame({})
Wiki['Rank']=Rank
Wiki['Name']=Name
Wiki['Artist']=Artist
Wiki['Upload Date']=UploadDate
Wiki['Views']=Views

In [34]:
Wiki

,Rank,Name,Artist,Upload Date,Views
0,1.,"""Baby Shark Dance""[3]",Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",10.92
1,2.,"""Despacito""[6]",Luis Fonsi,"January 12, 2017",7.90
2,3.,"""Johny Johny Yes Papa""[12]",LooLoo Kids,"October 8, 2016",6.39
3,4.,"""Shape of You""[13]",Ed Sheeran,"January 30, 2017",5.76
4,5.,"""See You Again""[15]",Wiz Khalifa,"April 6, 2015",5.56
5,6.,"""Bath Song""[20]",Cocomelon – Nursery Rhymes,"May 2, 2018",5.50
6,7.,"""Phonics Song with Two Words""[21]",ChuChu TV,"March 6, 2014",4.71
7,8.,"""Uptown Funk""[22]",Mark Ronson,"November 19, 2014",4.62
8,9.,"""Learning Colors – Colorful Eggs on a Farm""[23]",Miroshka TV,"February 27, 2018",4.59
9,10.,"""Masha and the Bear – Recipe for Disaster""[24]",Get Movies,"January 31, 2012",4.50
10,11.,"""Gangnam Style""[25]",Psy,"July 15, 2012",4.47
11,12.,"""Wheels on the Bus""[30]",Cocomelon – Nursery Rhymes,"May 24, 2018",4.18
12,13.,"""Dame Tu Cosita""[31]",El Chombo,"April 5, 2018",3.97
13,14.,"""Sugar""[32]",Maroon 5,"January 14, 2015",3.72
14,15.,"""Roar""[33]",Katy Perry,"September 5, 2013",3.61
15,16.,"""Counting Stars""[34]",OneRepublic,"May 31, 2013",3.60
16,17.,"""Sorry""[35]",Justin Bieber,"October 22, 2015",3.56
17,18.,"""Thinking Out Loud""[36]",Ed Sheeran,"October 7, 2014",3.47
18,19.,"""Axel F""[37]",Crazy Frog,"June 16, 2009",3.42
19,20.,"""Girls Like You""[38]",Maroon 5,"May 31, 2018",3.31
20,21.,"""Faded""[39]",Alan Walker,"December 3, 2015",3.30
21,22.,"""Dark Horse""[40]",Katy Perry,"February 20, 2014",3.30
22,23.,"""Baa Baa Black Sheep""[41]",Cocomelon – Nursery Rhymes,"June 25, 2018",3.28
23,24.,"""Let Her Go""[42]",Passenger,"July 25, 2012",3.26
24,25.,"""Bailando""[43]",Enrique Iglesias,"April 11, 2014",3.23
25,26.,"""Lean On""[44]",Major Lazer,"March 22, 2015",3.23
26,27.,"""Perfect""[45]",Ed Sheeran,"November 9, 2017",3.20
27,28.,"""Shake It Off""[46]",Taylor Swift,"August 18, 2014",3.19
28,29.,"""Waka Waka (This Time for Africa)""[47]",Shakira,"June 4, 2010",3.18
29,30.,"""Mi Gente""[48]",J Balvin,"June 29, 2017",3.10

In [36]:
driver.close()

# 2. Scrape the details team India’s international fixtures from bcci.tv. Url = https://www.bcci.tv/.
You need to find following details:
A) Match title (I.e. 1st ODI)
B) Series
C) Place
D) Date
E) Time
Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [37]:
driver=webdriver.Chrome('chromedriver.exe')

# Getting the webpage of mentioned url 
url=('https://www.bcci.tv/')
driver.get(url)

In [41]:
#clickin on International tab
International = driver.find_element_by_xpath('/html/body/nav/div[1]/div[2]/ul[1]/li[2]/a') # click button
International.click()

In [55]:
#Creating Empty List
Name=[]
Series=[]
Place=[]
Date=[]
Time=[]
#Scrapping Name
try:
    for i in driver.find_elements_by_xpath('//span[@class="matchOrderText ng-binding ng-scope"]'):
        Name.append(i.text.replace('-',""))
except NoSuchElementException:
    Name.append('-')
#Scrapping Series
try:
    
    for i in driver.find_elements_by_xpath('//span[@class="ng-binding"]'):
        Series.append(i.text)
except NoSuchElementException:
    Series.append('-')
#scrapping Place
try:
    for i in driver.find_elements_by_xpath('//span[@class="ng-binding ng-scope"]'):
        Place.append(i.text)
except NoSuchElementException:
    Place.append('-')
#Scrapping Date
try:
    for i in driver.find_elements_by_xpath('//h5[@class="ng-binding"]'):
        Date.append(i.text)
except NoSuchElementException:
    Date.append('-')
#Scrapping Time
try:
    for i in driver.find_elements_by_xpath('//h5[@class="text-right ng-binding"]'):
        Time.append(i.text.replace('IST',""))
except NoSuchElementException:
    Time.append('-')

    
# Create Dataframe

Fixtures=pd.DataFrame({})
Fixtures['Title']=Series
Fixtures['Name']=Name
Fixtures['Place']=Place
Fixtures['Date']=Date
Fixtures['Time']=Time
Fixtures

,Title,Name,Place,Date,Time
0,INDIA TOUR OF ENGLAND ODI SERIES 2022,2nd ODI,"Lord's Cricket Ground,",14 JUL 2022,5:30 PM
1,INDIA TOUR OF ENGLAND ODI SERIES 2022,3rd ODI,"Old Trafford,",17 JUL 2022,3:30 PM
2,INDIA TOUR OF WEST INDIES ODI SERIES 2022,1st ODI,"Queens Park Oval,",22 JUL 2022,7:00 PM
3,INDIA TOUR OF WEST INDIES ODI SERIES 2022,2nd ODI,"Queens Park Oval,",24 JUL 2022,7:00 PM
4,INDIA TOUR OF WEST INDIES ODI SERIES 2022,3rd ODI,"Queens Park Oval,",27 JUL 2022,7:00 PM
5,INDIA TOUR OF WEST INDIES T20 SERIES 2022,1st T20I,"Brian Lara Stadium,",29 JUL 2022,8:00 PM
6,INDIA TOUR OF WEST INDIES T20 SERIES 2022,2nd T20I,"Warner Park,",1 AUG 2022,8:00 PM
7,INDIA TOUR OF WEST INDIES T20 SERIES 2022,3rd T20I,"Warner Park,",2 AUG 2022,8:00 PM

In [126]:
driver.close()

# 3. Scrape the details of selenium exception from guru99.com. Url = https://www.guru99.com/
You need to find following details:
A) Name
B) Description
Note: - From guru99 home page you have to reach to selenium exception handling page through code.

In [117]:
driver=webdriver.Chrome('chromedriver.exe')

In [118]:
# get webpage
driver.get("https://www.guru99.com/")
driver.maximize_window()

In [119]:
# Click Selenium Button
Selenium = driver.find_element_by_xpath('//div[@class = "wp-block-kadence-column inner-column-2 kadence-column_f38d98-3a"]') # click button
try:
    Selenium.click()
except ElementNotInteractableException:#handling element not clickable exception
    driver.get(Selenium.get_attribute('href'))
time.sleep(3)

In [112]:
#driver.find_element_by_xpath("/html/body/div[6]/div/div[1]/div/div/div/div/div[1]").click()

In [120]:
# Click selenium exception handling  Button
exception_handling = driver.find_element_by_xpath("//a[@title='Selenium Exception Handling (Common Exceptions List)']")
try:
    exception_handling.click()
except ElementNotInteractableException:  #if the above code doesn't work/is not clickable then, the below code will handle it
    driver.get(exception_handling.get_attribute('href'))

In [123]:
names=[]
desc=[]
#Scrapping Name
for i in driver.find_elements_by_xpath('//table[@class="table table-striped"]/tbody/tr/td[1]'):
    names.append(i.text)
for i in driver.find_elements_by_xpath('//table[@class="table table-striped"]/tbody/tr/td[2]'):
    desc.append(i.text)

In [125]:
Selenium_Exception=pd.DataFrame()
Selenium_Exception['Exception name']=names
Selenium_Exception['Description']=desc
Selenium_Exception

,Exception name,Description
0,ElementNotVisibleException,This type of Selenium exception occurs when an...
1,ElementNotSelectableException,This Selenium exception occurs when an element...
2,NoSuchElementException,This Exception occurs if an element could not ...
3,NoSuchFrameException,This Exception occurs if the frame target to b...
4,NoAlertPresentException,This Exception occurs when you switch to no pr...
5,NoSuchWindowException,This Exception occurs if the window target to ...
6,StaleElementReferenceException,This Selenium exception occurs happens when th...
7,SessionNotFoundException,The WebDriver is acting after you quit the bro...
8,TimeoutException,Thrown when there is not enough time for a com...
9,WebDriverException,This Exception takes place when the WebDriver ...
10,ConnectionClosedException,This type of Exception takes place when there ...
11,ElementClickInterceptedException,The command may not be completed as the elemen...
12,ElementNotInteractableException,This Selenium exception is thrown when any ele...
13,ErrorInResponseException,This happens while interacting with the Firefo...
14,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
15,ImeActivationFailedException,This expectation will occur when IME engine ac...
16,ImeNotAvailableException,It takes place when IME support is unavailable.
17,InsecureCertificateException,Navigation made the user agent to hit a certif...
18,InvalidArgumentException,It occurs when an argument does not belong to ...
19,InvalidCookieDomainException,This happens when you try to add a cookie unde...
20,InvalidCoordinatesException,This type of Exception matches an interacting ...
21,InvalidElementStateExceptio,It occurs when command can’t be finished when ...
22,InvalidSessionIdException,This Exception took place when the given sessi...
23,InvalidSwitchToTargetException,This occurs when the frame or window target to...
24,JavascriptException,This issue occurs while executing JavaScript g...
25,JsonException,It occurs when you afford to get the session w...
26,NoSuchAttributeException,This kind of Exception occurs when the attribu...
27,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
28,NoSuchContextException,ContextAware does mobile device testing.
29,NoSuchCookieException,This Exception occurs when no cookie matching ...
30,NotFoundException,This Exception is a subclass of WebDriverExcep...
31,RemoteDriverServerException,This Selenium exception is thrown when the ser...
32,ScreenshotException,It is not possible to capture a screen.
33,SessionNotCreatedException,It happens when a new session could not be suc...
34,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
35,UnexpectedTagNameException,Happens if a support class did not get a web e...
36,UnhandledAlertException,This expectation occurs when there is an alert...
37,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
38,UnknownMethodException,This Exception happens when the requested comm...
39,UnreachableBrowserException,This Exception occurs only when the browser is...
40,UnsupportedCommandException,This occurs when remote WebDriver does n’t sen...

In [265]:
driver.close()

# 4.Scrape the details of State-wise GDP of India from statisticstime.com. Url = http://statisticstimes.com/
You have to find following details:
A) Rank

B) State

C) GSDP(18-19)

D) GSDP(17-18)

E) Share(2017)

F) GDP($ billion)
Note: - From statisticstimes home page you have to reach to economy page through code.

In [270]:
driver=webdriver.Chrome('chromedriver.exe')

In [267]:
driver.maximize_window()
driver.get('https://www.statisticstimes.com')
time.sleep(3)

In [269]:
driver.find_element_by_xpath('/html/body/div[1]/div/a').click()

In [29]:
 #Clicking on Economy button
driver.find_element_by_xpath("//div[@class='navbar']/div[2]/button").click()

In [30]:
#Clicking on India
driver.find_element_by_xpath("//div[@class='dropdown-content']/a[3]").click()

In [156]:
# Clicking on GDP of Indian Economy
GDP = driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[2]/ul/li[1]/a').click()
time.sleep(3)

In [ ]:
# Creating empty list
Rank = []
State = []
GSDP1 = []
GSDP2 = []
Share = []
GDPbillion = []
# Scraping Rank
try:
    for i in driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[1]"):
        Rank.append(i.text)
except NoSuchElementException:
    Rank.append("_")
# Scraping State
try:
    for i in driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[2]"):
        State.append(i.text)
except NoSuchElementException:
    State.append("_")
# Scraping GSDP at current price (18-19)
try:
    for i in driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[4]"):
        GSDP2.append(i.text)
except NoSuchElementException:
    GSDP2.append("_")
# Scraping Share (18-19)
try:
    for i in driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[5]"):
        Share.append(i.text)
except NoSuchElementException:
    Share.append("_")
# Scraping GDP $ billion
try:
    for i in driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[6]"):
        GDPbillion.append(i.text)
except NoSuchElementException:
    GDPbillion.append("_")

In [271]:
driver.close()

# 5. Scrape the details of trending repositories on Github.com. Url = https://github.com/
You have to find the following details:
A) Repository title
B) Repository description
C) Contributors count
D) Language used
ASSIGNMENT
Note: - From the home page you have to click on the trending option from Explore menu through code.

In [32]:
driver=webdriver.Chrome('chromedriver.exe')

In [33]:
driver.maximize_window()
url=('https://github.com/')
driver.get(url)

In [37]:
# Click on explore

explore = driver.find_element_by_xpath('//li[@class = "mr-0 mr-lg-3 position-relative flex-wrap flex-justify-between flex-items-center border-bottom border-lg-bottom-0 d-block d-lg-flex flex-lg-nowrap flex-lg-items-center"][4]')
try:
    explore.click()
    time.sleep(5)
except ElementNotInteractableException:
    driver.get(explore.get_attribute('href'))

In [38]:
# Click on Trending

trending = driver.find_element_by_xpath('//*[@href="/trending"]')
try:
    driver.get(trending.get_attribute('href'))
except ElementNotInteractableException:
    driver.get(trending.get_attribute('href'))

In [92]:
#Creating empty list
#Creating empty list
URLs = []
repository_title = []
Description = []
Contributors = []
Language = []
lang = []

In [93]:
#Fetching urls for each repository
repository = driver.find_elements_by_xpath("//h1[@class = 'h3 lh-condensed']//a")
for i in repository:
    URLs.append(i.get_attribute("href"))

In [94]:
# Scraping Repository Title data
title = driver.find_elements_by_xpath("//h1[@class = 'h3 lh-condensed']")
for i in title:
    repository_title.append(i.text)

In [95]:
# Scraping data from all repository page
for i in URLs:
    driver.get(i)
    time.sleep(2)
    
        # Scraping Repository Description data
    try:
        desc = driver.find_element_by_xpath("//p[@class='f4 my-3']")
        Description.append(desc.text)
    except NoSuchElementException:
        Description.append('-')
        
        
    # Scraping Contributors Count data
    try:
        contributor = driver.find_element_by_xpath("//*[contains(text(),'    Contributors ')]")
        Contributors.append(contributor.text.replace('Contributors',''))
    except NoSuchElementException:
        Contributors.append('-')
        
        
    # Scraping Languages used data
    lang=[]
    try:
        for i in driver.find_elements_by_xpath('//span[@class="color-fg-default text-bold mr-1"]'):
            lang.append(i.text)
        Language.append(lang)
    except NoSuchElementException:
        lang.append('-')

In [96]:
print(len(repository_title),len(Description),len(Contributors),len(Language))

25 25 25 25

In [97]:
#DATA FRAMEING
Github=pd.DataFrame({})
Github['Repository title'] = repository_title
Github['Repository description'] = Description
Github['Contributors count'] = Contributors
Github['Language used'] = Language
Github

,Repository title,Repository description,Contributors count,Language used
0,rust-lang / rustlings,🦀 Small exercises to get you used to reading a...,245,"[Rust, Shell, PowerShell]"
1,logto-io / logto,"🧑‍🚀 Logto helps you build the sign-in, auth, a...",11,"[TypeScript, SCSS, Other]"
2,codecrafters-io / build-your-own-x,Master programming by recreating your favorite...,75,[]
3,srush / GPU-Puzzles,Solve puzzles. Learn CUDA.,2,"[Jupyter Notebook, Python]"
4,ytdl-org / youtube-dl,Command-line program to download videos from Y...,768,"[Python, Other]"
5,jart / cosmopolitan,build-once run-anywhere c library,32,"[C, Assembly, Shell, Lua, Makefile, Emacs Lisp..."
6,TheAlgorithms / JavaScript,Algorithms and Data Structures implemented in ...,224,[JavaScript]
7,trpc / trpc,🧙‍♀️ Move Fast and Break Nothing. End-to-end t...,100,"[TypeScript, JavaScript, CSS]"
8,dair-ai / ML-YouTube-Courses,📺 A place to discover the latest machine learn...,8,[]
9,fossabot / typoraCracker,A patch and keygen tools for typora.,2,"[Python, JavaScript]"
10,shengcaishizhan / kkndme_tianya,天涯 kkndme 神贴聊房价,-,[]
11,bambulab / BambuStudio,PC Software for BambuLab's 3D printers,3,"[C++, C, JavaScript, HTML, Perl, CMake, Other]"
12,Moataz-Elmesmary / Data-Science-Roadmap,Data Science Roadmap from A to Z,-,[]
13,freqtrade / freqtrade,"Free, open source crypto trading bot",225,"[Python, Jinja, Shell, Jupyter Notebook, Docke..."
14,Anduin2017 / HowToCook,程序员在家做饭方法指南。Programmer's guide about how to co...,281,[Shell]
15,nim-lang / Nim,Nim is a statically typed compiled systems pro...,670,"[Nim, HTML, C, CSS, Python, C++, Other]"
16,adiwajshing / Baileys,Lightweight full-featured WhatsApp Web + Multi...,85,"[JavaScript, TypeScript]"
17,enaqx / awesome-react,A collection of awesome things regarding React...,604,[]
18,fatedier / frp,A fast reverse proxy to help you expose a loca...,80,"[Go, Vue, JavaScript, Shell, HTML, Makefile, L..."
19,wailsapp / wails,Create beautiful applications using Go,100,"[Go, C++, C, HTML, JavaScript, Objective-C, Ot..."
20,github / docs,The open-source repo for docs.github.com,"1,335","[JavaScript, TypeScript, HTML, Other]"
21,Hunlongyu / ZY-Player,▶️ 跨平台桌面端视频资源播放器.简洁无广告.免费高颜值. 🎞,9,"[Vue, SCSS, JavaScript, HTML]"
22,Asabeneh / 30-Days-Of-React,30 Days of React challenge is a step by step g...,8,"[JavaScript, HTML, Other]"
23,smartcontractkit / full-blockchain-solidity-co...,"Learn Blockchain, Solidity, and Full Stack Web...",17,[]
24,mgunyho / tere,Terminal file explorer,4,"[Rust, Shell]"

In [98]:
driver.close()

#  6. Scrape the details of top 100 songs on billiboard.com. Url = https:/www.billboard.com/
You have to find the following details:
A) Song name
B) Artist name
C) Last week rank
D) Peak rank
E) Weeks on board
Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [180]:
driver=webdriver.Chrome('chromedriver.exe')
driver.maximize_window()

In [181]:
# Getting the webpage of mentioned url 
url=('https://www.billboard.com/')
driver.get(url)

In [182]:
#Clicking on charts
charts=driver.find_element_by_xpath('//*[@id="main-wrapper"]/header/div[2]/div/nav/ul/li[1]/a').click()

In [183]:
# Creating empty lists
Song_Name = []
Artist_Name = []
Last_week_rank = []
Peak_rank = []
Weeks_on_board = []

In [185]:
# Scraping name
for i in driver.find_elements_by_xpath('//li[@class="lrv-u-width-100p"]'):
    Song_Name.append(i.text)
len(Song_Name)

100

In [186]:
#Scrappin Artist name 1 st one
Artist_Name.append(driver.find_element_by_xpath("//span[@class='c-label  a-no-trucate a-font-primary-s lrv-u-font-size-14@mobile-max u-line-height-normal@mobile-max u-letter-spacing-0021 lrv-u-display-block a-truncate-ellipsis-2line u-max-width-330 u-max-width-230@tablet-only u-font-size-20@tablet']").text)

In [187]:
#Remainig Artist Name
artistTag=driver.find_elements_by_xpath("//span[@class='c-label  a-no-trucate a-font-primary-s lrv-u-font-size-14@mobile-max u-line-height-normal@mobile-max u-letter-spacing-0021 lrv-u-display-block a-truncate-ellipsis-2line u-max-width-330 u-max-width-230@tablet-only']")
Artist_Name.extend([i.text for i in artistTag])

In [188]:
#Scapping Rank
rank=[]
rankTag=driver.find_elements_by_xpath("//span[@class='c-label  a-font-primary-bold-l a-font-primary-m@mobile-max u-font-weight-normal@mobile-max lrv-u-padding-tb-050@mobile-max u-font-size-32@tablet']")
rank.extend([i.text for i in rankTag[:3]])

In [189]:
#Remaining RAnk
Rank=[]
RankTag=driver.find_elements_by_xpath("//span[@class='c-label  a-font-primary-m lrv-u-padding-tb-050@mobile-max']")
Rank.extend([i.text for i in RankTag])

In [190]:
# removing ''
for i in Rank:
    if i=='':
        Rank.remove(i)

In [191]:
# slicing as per requirement
lastweekpos=Rank[0::3]
lastweekpos.insert(0,rank[0])
peakPos=Rank[1::3]
peakPos.insert(0,rank[1])
weeksonBoard=Rank[2::3]
weeksonBoard.insert(0,rank[2])

In [167]:
#check length of all
len(Song_Name),len(Artist_Name),len(lastweekpos),len(peakPos),len(weeksonBoard)

(300, 100, 133, 133, 133)

In [192]:
# Create Dataframe
df=pd.DataFrame()
df['SongName']=Song_Name[0:100]
df['ArtistName']=Artist_Name
df['Last Week']=lastweekpos[0:100]
df["PeekPosition"]=peakPos[0:100]
df['Weeks On board']=weeksonBoard[0:100]

In [193]:
df

,SongName,ArtistName,Last Week,PeekPosition,Weeks On board
0,As It Was\nHarry Styles\n1\n1\n14,Harry Styles,1,1,14
1,About Damn Time\nLizzo\n3\n2\n12,Lizzo,3,2,12
2,First Class\nJack Harlow\n2\n1\n13,Jack Harlow,2,1,13
3,Running Up That Hill (A Deal With God)\nKate B...,Kate Bush,6,4,26
4,Wait For U\nFuture Featuring Drake & Tems\n4\n...,Future Featuring Drake & Tems,4,1,10
...,...,...,...,...,...
95,Best Thing Since Backroads\nJake Owen\n-\n96\n1,Jake Owen,-,82,1
96,"U-Digg\nLil Baby, 42 Dugg & Veeze\n82\n52\n3","Lil Baby, 42 Dugg & Veeze",,,
97,Unstoppable\nSia\n-\n98\n1,Sia,-,83,1
98,Rich Minion\nYeat\n-\n99\n1,Yeat,,,
99,Bad Habit\nSteve Lacy\n-\n100\n1,Steve Lacy,81,26,4

In [194]:
driver.close()

# 7. Scrape the details of Data science recruiters from naukri.com. Url = https://www.naukri.com/
You have to find the following details:
A) Name
B) Designation
C) Company
D) Skills they hire for
E) Location
Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and click on search. All this should be done through code

In [230]:
driver=webdriver.Chrome('chromedriver.exe')

In [231]:
driver.maximize_window()
# Getting the webpage of mentioned url 
url=('https://www.naukri.com/')
driver.get(url)
time.sleep(2)

In [232]:
#Fetching urls to navigate recruiter page
recruiter = driver.find_element_by_xpath('//a[@title="Search Jobs"]')
page_url = recruiter.get_attribute("href")

driver.get(page_url)
time.sleep(3)

In [235]:
#Fetching urls to navigate recruiter page
recruiter = driver.find_element_by_xpath('/html/body/div[1]/div/ul/li[2]/a')
page_url = recruiter.get_attribute("href")

driver.get(page_url)
time.sleep(3)

In [237]:
# Fetching search button, sending keys and clicking on it
search = driver.find_element_by_xpath("//div[@class='inpWrap']//input") 
search.send_keys("Data science ")           
btn = driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[1]/div[1]/form/div[1]/button').click()     
time.sleep(3)

In [238]:
#Creating empty lists
Name = []
Designation = []
Company = []
Skills = []
Location = []

In [239]:
#Scraping data of Names
for i in driver.find_elements_by_xpath("//span[@class='fl ellipsis']"):
    Name.append(i.text)
time.sleep(3)
#Scraping data of Designation

In [240]:
for i in driver.find_elements_by_xpath("//span[@class='ellipsis clr']"):
    Designation.append(i.text)
#Scraping data of company name
for i in driver.find_elements_by_xpath("//div[@class='vcard']//p[1]/a[2]"):
    Company.append(i.text)

#Scraping data of locations
for i in driver.find_elements_by_xpath("//div[@class='vcard']//p[1]//span"):
    Location.append(i.text)
time.sleep(3)

In [241]:
print(len(Name),len(Designation),len(Company),len(Location))

50 50 50 149

In [242]:
# Creating dataframe for scraped data
Naukri=pd.DataFrame({})
Naukri['Name'] = Name
Naukri['Designation'] = Designation
Naukri['Company'] = Company
Naukri['Location'] = Location[:50]
Naukri

,Name,Designation,Company,Location
0,Rajiv Raj,Director,CreditVidya,Rajiv Raj
1,Sharmistha Maity,Company Recruiter,ICA Edu Skills Pvt. Ltd.,Director
2,Malvika Bhandari,Talent Acquisition Consultant,IMS Proschool Pvt. Ltd,Mumbai
3,Fgts Recruitment,Company Recruiter,FUSION GLOBAL TECHNOLOGIES AND SOLUTIONS...,Sharmistha Maity
4,Vineet P,Opportunity Communicator,Dell Technologies,Company Recruiter
5,Silky Sethi,Company Recruiter,ZS Associates {India} Pvt Ltd,Kolkata
6,Tracy Raina,Senior HR Executive,Quatrro Global Services Pvt. Ltd.,Malvika Bhandari
7,HR Carzonrent,Company Recruiter,Carzonrent (India) Pvt Ltd,Talent Acquisition Consultant
8,Deepti Nagle,Recruitment Executive,Nityo Infotech Services Pvt. Ltd.,Pune
9,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,Fgts Recruitment
10,Aakash Harit,HR Manager,Data Science Network,Company Recruiter
11,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,Chennai
12,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,Vineet P
13,subhas patel,Founder CEO,LibraryXProject,Opportunity Communicator
14,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,Bengaluru / Bangalore
15,Institute for Financial Management and Resear,Programme Manager,IFMR,Silky Sethi
16,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,Company Recruiter
17,Vaishnavi Kudalkar,HR Executive,Codeachive learning,Pune
18,Priyanka Akiri,HR Manager,Infinitive Software Solutions,Tracy Raina
19,Kalpana Dumpala,Executive Hiring,Innominds Software,Senior HR Executive
20,Mubarak,Company HR,MoneyTap,Gurgaon
21,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,HR Carzonrent
22,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,Company Recruiter
23,Kapil Devang,HR Manager,BISP Solutions,Delhi
24,Sakshi Chhikara,Assistant Manager HR,BIZ INFOTECNO PRIVATE LIMITED,Deepti Nagle
25,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,Recruitment Executive
26,Manisha Yadav,HR Executive,Easi Tax,Pune
27,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,shravan Kumar Gaddam
28,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,Company Recruiter
29,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,Hyderabad / Secunderabad
30,Rithika dadwal,HR Recruiter,Affine Analytics,Aakash Harit
31,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,HR Manager
32,Shaun Rao,Manager Human Resources,Exela Technologies,Delhi
33,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd",Anik Agrawal
34,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,Company Recruiter
35,Asif Lucknowi,Director,Weupskill- Live Wire India,Ahmedabad
36,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,MARSIAN Technologies LLP
37,Dr. S. Prasanna Devi,Professor and Head,SRM Institute of Science and Technology,Company HR
38,kumar,Proprietor,trainin,Pune
39,Sunil Vedula,CEO,Nanoprecise Sci Corp,subhas patel
40,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,Founder CEO
41,Dhruv Dev Dubey,Company Recruitment Head,Confidential,UK - (london)
42,Rajani Nagaraj,HR Manager,WildJasmine,Abhishek - Only Analytics Hiring - India and
43,Avodha,Business Development Associate,Nikitha Palaparthi,Recruitment Lead Consultant
44,SREEDHAR,Recruitment Consultant,JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED,Vadodara / Baroda
45,Rutuja Pawar,Technical Recruiter,Demand Matrix,Institute for Financial Management and Resear
46,Priya Khare,Senior Manager,Independent Consultant,Programme Manager
47,Amit Sharma,Consultant,ASCO consulting,Chennai
48,Kanan,senior technology instructor,NY INST,Balu Ramesh
49,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,HR Administrator

# Q8: Scrape the details of Highest selling novels.

Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greycompare/

You have to find the following details:

A) Book name

B) Author name

C) Volumes sold

D) Publisher

E) Genre

In [243]:
# connect to webdriver
driver = webdriver.Chrome("chromedriver.exe")

In [244]:
# get webpage
driver.get("https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare")
driver.maximize_window()

In [245]:
#Creating empty list
Bookname = []
Authorname = []
Volumessold = []
Publisher = []
Genre = []

In [246]:
#scraping book names data
for i in driver.find_elements_by_xpath("//tbody//tr/td[2]"):
    Bookname.append(i.text)
#Scraping author names data
for i in driver.find_elements_by_xpath("//tbody/tr/td[3]"):
    try:
        if i.text == '0' : raise NoSuchElementException
        Authorname.append(i.text)
    except NoSuchElementException:
        Authorname.append('-')
time.sleep(1)
#Scraping data of volumes sold
for i in driver.find_elements_by_xpath("//tbody/tr/td[4]"):
    Volumessold.append(i.text)
#Scraping data of publisher names
for i in driver.find_elements_by_xpath("//tbody/tr/td[5]"):
    Publisher.append(i.text)
    
#Scraping data of genre
for i in driver.find_elements_by_xpath("//tbody/tr/td[6]"):
    Genre.append(i.text)

In [247]:
#Creating dataframe for scraped data
Novels=pd.DataFrame({})
Novels['Book Name'] = Bookname
Novels['Author'] = Authorname
Novels['Volume sold'] = Volumessold
Novels['Publisher'] = Publisher
Novels['Genre'] = Genre
Novels

,Book Name,Author,Volume sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

In [248]:
driver.close()

# Q9: Scrape the details most watched tv series of all time from imdb.com.

Url = https://www.imdb.com/list/ls095964455/

You have to find the following details:

A) Name

B) Year span

C) Genre

D) Run time

E) Ratings

F) Votes

In [249]:
# connect to webdriver
driver = webdriver.Chrome("chromedriver.exe")

In [250]:
# get webpage
driver.get("https://www.imdb.com/list/ls095964455/")
driver.maximize_window()

In [252]:
#Creating empty lists.
Name = []
Year_span = []
Genre = []
Run_time = []
Ratings = []
Votes = []
#Scraping data of Names
for i in driver.find_elements_by_xpath("//h3[@class='lister-item-header']/a"):
    Name.append(i.text)
#Scraping data of Year span
for i in driver.find_elements_by_xpath("//span[@class='lister-item-year text-muted unbold']"):
    Year_span.append(i.text)
#Scraping data of Run time
for i in driver.find_elements_by_xpath("//span[@class='runtime']"):
    Run_time.append(i.text)
#Scraping data of Ratings
for i in driver.find_elements_by_xpath("//div[@class='ipl-rating-star small']//span[2]"):
    Ratings.append(i.text)
#Scraping data of genre
for i in driver.find_elements_by_xpath("//span[@class='genre']"):
    Genre.append(i.text)
#Scraping data of votes
for i in driver.find_elements_by_xpath("//div[@class='lister-item-content']//p[4]/span[2]"):
    Votes.append(i.text)

In [253]:
# Creating dataframe for scraped data
TVseries=pd.DataFrame({})
TVseries['Name'] = Name
TVseries['Year Span'] = Year_span
TVseries['Genre'] = Genre
TVseries['Run Time'] = Run_time
TVseries['Ratings'] = Ratings
TVseries['Votes'] = Votes
TVseries

,Name,Year Span,Genre,Run Time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"2,009,924"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"1,092,021"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"955,342"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"285,612"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"245,256"
...,...,...,...,...,...,...
95,Reign,(2013–2017),Drama,42 min,7.4,"49,106"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"59,897"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.1,"192,295"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"40,608"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"231,349"

In [254]:
driver.close()

# Q10: Details of Datasets from UCI machine learning repositories.

Url = https://archive.ics.uci.edu/

You have to find the following details:

A) Dataset name

B) Data type

C) Task

D) Attribute type

E) No of instances

F) No of attribute

G) Year

Note: - from the home page you have to go to the Show All Dataset page through code

In [255]:
# connect to webdriver
driver = webdriver.Chrome("chromedriver.exe")

In [256]:
# get webpage
driver.get(" https://archive.ics.uci.edu/")
driver.maximize_window()

In [257]:
# Finding view all dataset button from the webpage
viewall_dataset = driver.find_element_by_xpath("//tbody[1]//tr/td[2]/span[2]/a")    
page_url = viewall_dataset.get_attribute("href")
driver.get(page_url)

In [258]:
# Fetching page urls of all datasets 
view_list = driver.find_element_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[1]/tbody/tr/td[2]/p/a")  
list_url = view_list.get_attribute("href")           
driver.get(list_url)

In [259]:
# Fetching urls for each dataset
dataset_url = driver.find_elements_by_xpath("//p[@class='normal']//b/a")    

urls = []     
for i in dataset_url:
    urls.append(i.get_attribute("href"))

In [262]:
#Creating empty lists
Dataset_name = []
Data_type = []
Task = []
Attribute_type = []
No_of_instances = []
No_of_attributes = []
Year = []

In [263]:
for i in urls:
    driver.get(i)
    time.sleep(2)
    
    #Scraping Dataset name
    try: 
        dataset_name = driver.find_element_by_xpath("//span[@class='heading']")
        Dataset_name.append(dataset_name.text)
    except NoSuchElementException:
        Dataset_name.append('-')
    
    
    #Scraping data type
    try:
        data_type = driver.find_element_by_xpath("//table[@border='1']//tbody/tr/td[2]")
        if data_type.text == "N/A": raise NoSuchElementException
        Data_type.append(data_type.text)
    except NoSuchElementException:
        Data_type.append('-')
    
    
    #scraping Task
    try:
        task = driver.find_element_by_xpath("//table[@border='1']//tbody/tr[3]/td[2]")
        if task.text == "N/A": raise NoSuchElementException
        Task.append(task.text)
    except NoSuchElementException:
        Task.append('-')
    
    
    # Scraping Attribute type
    try:
        attribute_type = driver.find_element_by_xpath("//table[@border='1']//tbody/tr[2]/td[2]")
        if attribute_type.text == "N/A": raise NoSuchElementException
        Attribute_type.append(attribute_type.text)
    except NoSuchElementException:
        Attribute_type.append('-')
    
    
    # Scraping No of instances
    try:
        instances = driver.find_element_by_xpath("//table[@border='1']//tbody/tr/td[4]")
        if instances.text == "N/A": raise NoSuchElementException
        No_of_instances.append(instances.text)
    except NoSuchElementException:
        No_of_instances.append('-')
    
    
    # Scraping No of attributes
    try:
        attribute = driver.find_element_by_xpath("//table[@border='1']//tbody/tr[2]/td[4]")
        if attribute.text == "N/A": raise NoSuchElementException
        No_of_attributes.append(attribute.text)
    except NoSuchElementException:
        No_of_attributes.append('-')
    
    
    # Scraping year
    try:
        year = driver.find_element_by_xpath("//table[@border='1']//tbody/tr[2]/td[6]")
        if year.text == "N/A": raise NoSuchElementException
        Year.append(year.text[:4])
    except NoSuchElementException:
        Year.append('-')

In [264]:
# Creating dataframe for scraped data
ML=pd.DataFrame({})
ML['Data Name'] = Dataset_name[:643]
ML['Data Type'] = Data_type[:643]
ML['Task'] = Task[:643]
ML['Attribute type'] = Attribute_type[:643]
ML['No of instance'] = No_of_instances
ML['No of attributes'] = No_of_attributes[:643]
ML['Year'] = Year[:643]
ML

,Data Name,Data Type,Task,Attribute type,No of instance,No of attributes,Year
0,2.4 GHZ Indoor Channel Measurements Data Set,Multivariate,Classification,Real,7840,5,2018
1,"3D Road Network (North Jutland, Denmark) Data Set","Sequential, Text","Regression, Clustering",Real,434874,4,2013
2,3W dataset Data Set,"Multivariate, Time-Series","Classification, Clustering","Integer, Real",1984,8,2019
3,9mers from cullpdb Data Set,Sequential,"Classification, Regression",Real,158716,4,2021
4,: Simulated Data set of Iraqi tourism places D...,Multivariate,"Classification, Clustering",-,232,16,2020
...,...,...,...,...,...,...,...
617,Youtube cookery channels viewers comments in H...,"Multivariate, Text",Classification,-,9800,3,2019
618,YouTube Multiview Video Games Dataset Data Set,"Multivariate, Text","Classification, Clustering","Integer, Real",120000,1000000,2013
619,YouTube Spam Collection Data Set,Text,Classification,-,1956,5,2017
620,Z-Alizadeh Sani Data Set,-,Classification,"Integer, Real",303,56,2017
621,Zoo Data Set,Multivariate,Classification,"Categorical, Integer",101,17,1990